############################################################
##################### General Settings #####################
############################################################
set -sg escape-time 5
set -g default-terminal xterm-256color
set -as terminal-features ",xterm-256color:RGB"
set -g mouse on
set -g repeat-time 1000

# Reload tmux with prefix-r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "config reloaded"

# Don't exit from tmux when closing a session
set -g detach-on-destroy off

############################################################
########################## Panes ###########################
############################################################
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -r H resize-pane -L 7
bind -r J resize-pane -D 7
bind -r K resize-pane -U 7
bind -r L resize-pane -R 7
bind -rn M-H resize-pane -L 7
bind -rn M-J resize-pane -D 7
bind -rn M-K resize-pane -U 7
bind -rn M-L resize-pane -R 7

bind "/" split-window -h
bind "'" split-window -v
bind -n M-/ split-window -h
bind -n "M-'" split-window -v

bind x kill-pane
bind -n M-x kill-pane

############################################################
######################### Windows ##########################
############################################################
bind -n M-X confirm-before -p "kill-window #W? (y/n)" kill-window
bind X confirm-before -p "kill-window #W? (y/n)" kill-window
bind -n M-c new-window
bind -n M-p previous-window
bind -n M-n next-window

# Switch windows with corresponding numbers
set -g base-index 1
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9


############################################################
##################### External Plugins #####################
############################################################
### Vim Tmux Navigator #####################################
# https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind -n 'M-h' if-shell "$is_vim" 'send-keys M-h' 'select-pane -L'
bind -n 'M-j' if-shell "$is_vim" 'send-keys M-j' 'select-pane -D'
bind -n 'M-k' if-shell "$is_vim" 'send-keys M-k' 'select-pane -U'
bind -n 'M-l' if-shell "$is_vim" 'send-keys M-l' 'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind -T copy-mode-vi 'C-h' select-pane -L
bind -T copy-mode-vi 'C-j' select-pane -D
bind -T copy-mode-vi 'C-k' select-pane -U
bind -T copy-mode-vi 'C-l' select-pane -R
bind -T copy-mode-vi 'C-\' select-pane -l

### Sesh ###################################################
# https://github.com/joshmedeski/sesh
bind -n M-s display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' tv sesh

run ~/.config/tmux/plugins/theme.tmux
