after-login-command = []
after-startup-command = []

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 8
    inner.vertical =   8
    outer.left =       8
    outer.bottom =     8
    outer.top =        8
    outer.right =      8

[mode.main.binding]

    alt-cmd-ctrl-q = 'close --quit-if-last-window'
    alt-cmd-ctrl-enter = 'exec-and-forget open -n "/Applications/Ghostty.app"'
    alt-cmd-ctrl-f = 'exec-and-forget open "/System/Library/CoreServices/Finder.app"'
    alt-cmd-ctrl-b = 'exec-and-forget open -n "/Applications/Google Chrome.app"'
    alt-cmd-ctrl-m = 'exec-and-forget open "/System/Applications/Messages.app"'
    alt-cmd-ctrl-v = 'exec-and-forget open -n "/Applications/Visual Studio Code.app"'
    alt-cmd-ctrl-x = 'exec-and-forget open "/Applications/Webex.app"'
    alt-cmd-ctrl-slash = 'layout tiles horizontal vertical'
    alt-cmd-ctrl-comma = 'layout accordion horizontal vertical'
    alt-cmd-ctrl-h = 'focus left --boundaries-action wrap-around-the-workspace'
    alt-cmd-ctrl-j = 'focus down --boundaries-action wrap-around-the-workspace'
    alt-cmd-ctrl-k = 'focus up --boundaries-action wrap-around-the-workspace'
    alt-cmd-ctrl-l = 'focus right --boundaries-action wrap-around-the-workspace'
    alt-cmd-ctrl-shift-h = 'move left'
    alt-cmd-ctrl-shift-j = 'move down'
    alt-cmd-ctrl-shift-k = 'move up'
    alt-cmd-ctrl-shift-l = 'move right'
    alt-cmd-ctrl-minus = 'resize smart -50'
    alt-cmd-ctrl-equal = 'resize smart +50'
    alt-cmd-ctrl-1 = 'workspace 1'
    alt-cmd-ctrl-2 = 'workspace 2'
    alt-cmd-ctrl-3 = 'workspace 3'
    alt-cmd-ctrl-4 = 'workspace 4'
    alt-cmd-ctrl-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
    alt-cmd-ctrl-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
    alt-cmd-ctrl-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
    alt-cmd-ctrl-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
    alt-cmd-ctrl-tab = 'workspace-back-and-forth'
    alt-cmd-ctrl-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']
    alt-cmd-ctrl-shift-h = ['join-with left', 'mode main']
    alt-cmd-ctrl-shift-j = ['join-with down', 'mode main']
    alt-cmd-ctrl-shift-k = ['join-with up', 'mode main']
    alt-cmd-ctrl-shift-l = ['join-with right', 'mode main']
    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']
