#!/usr/bin/env bash

theme_path="$HOME/.config/rofi/themes/powermenu.rasi"

lock_cmd="swaylock"
logout_cmd="$HOME/.config/rofi/prompts/logout"
sleep_cmd="systemctl suspend"
restart_cmd="reboot"
shutdown_cmd="shutdown now"

if ! pgrep rofi; then
    option=$(printf "Lock\nSleep\nLog Out\nRestart\nShut Down" | rofi -dmenu -i -theme $theme_path -p "Power Menu")

    case "$option" in
    "Lock") $lock_cmd ;;
    "Sleep") $sleep_cmd ;;
    "Log Out") $logout_cmd ;;
    "Restart") reboot ;;
    "Shut Down") shutdown now ;;
    *) exit 1 ;;
    esac
else
    pkill rofi
fi
