$bg = rgb(222436)
$bgAlpha = 222436

$bgDark = rgb(1e2030)
$bgDarkAlpha = 1e2030

$bgDark1 = rgb(191B29)
$bgDark1Alpha = 191B29

$bgHighlight = rgb(2f334d)
$bgHighlightAlpha = 2f334d

$blue = rgb(82aaff)
$blueAlpha = 82aaff

$blue0 = rgb(3e68d7)
$blue0Alpha = 3e68d7

$blue1 = rgb(65bcff)
$blue1Alpha = 65bcff

$blue2 = rgb(0db9d7)
$blue2Alpha = 0db9d7

$blue5 = rgb(89ddff)
$blue5Alpha = 89ddff

$blue6 = rgb(b4f9f8)
$blue6Alpha = b4f9f8

$blue7 = rgb(394b70)
$blue7Alpha = 394b70

$comment = rgb(636da6)
$commentAlpha = 636da6

$cyan = rgb(86e1fc)
$cyanAlpha = 86e1fc

$dark3 = rgb(545c7e)
$dark3Alpha = 545c7e

$dark5 = rgb(737aa2)
$dark5Alpha = 737aa2

$fg = rgb(c8d3f5)
$fgAlpha = c8d3f5

$fgDark = rgb(828bb8)
$fgDarkAlpha = 828bb8

$fgGutter = rgb(3b4261)
$fgGutterAlpha = 3b4261

$green = rgb(c3e88d)
$greenAlpha = c3e88d

$green1 = rgb(4fd6be)
$green1Alpha = 4fd6be

$green2 = rgb(41a6b5)
$green2Alpha = 41a6b5

$magenta = rgb(c099ff)
$magentaAlpha = c099ff

$magenta2 = rgb(ff007c)
$magenta2Alpha = ff007c

$orange = rgb(ff966c)
$orangeAlpha = ff966c

$purple = rgb(fca7ea)
$purpleAlpha = fca7ea

$red = rgb(ff757f)
$redAlpha = ff757f

$red1 = rgb(c53b53)
$red1Alpha = c53b53

$teal = rgb(4fd6be)
$tealAlpha = 4fd6be

$terminalBlack = rgb(444a73)
$terminalBlackAlpha = 444a73

$yellow = rgb(ffc777)
$yellowAlpha = ffc777

$gitAdd = rgb(b8db87)
$gitAddAlpha = b8db87

$gitChange = rgb(7ca1f2)
$gitChangeAlpha = 7ca1f2

$gitDelete = rgb(e26a75)
$gitDeleteAlpha = e26a75
