#!/usr/bin/env bash

msg="Confirm: Log Out"
cmd="sway exit"

if [[ "$XDG_CURRENT_DESKTOP" = "niri" ]]; then
    cmd="niri msg action quit --skip-confirmation"
fi

~/.config/rofi/templates/confirm "$msg" "$cmd"
